/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.surau.app.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.compositeOver

/**
 * A named, hand-tuned Surau design-token palette. [SURAU_BASE] is the app default; [DEFAULT] keeps
 * the previous blue token set available as a selectable palette.
 */
enum class HeroPalette {
    SURAU_BASE,
    DEFAULT,
    MOUVE,
    SKY,
    MINT,
    DISCORD,
    UBER,
    AIRBNB,
}

private data class PaletteTokens(
    val name: String,
    val light: PaletteModeTokens,
    val dark: PaletteModeTokens,
)

private data class PaletteModeTokens(
    val background: Color,
    val foreground: Color,
    val muted: Color,
    val overlay: Color,
    val surface: Color,
    val surfaceSecondary: Color,
    val surfaceTertiary: Color,
    val surfaceHover: Color,
    val accent: Color,
    val accentForeground: Color,
    val accentSoft: Color,
    val accentSoftForeground: Color,
    val danger: Color,
    val dangerForeground: Color,
    val dangerSoft: Color,
    val dangerSoftForeground: Color,
    val success: Color,
    val successForeground: Color,
    val successSoft: Color,
    val successSoftForeground: Color,
    val warning: Color,
    val warningForeground: Color,
    val warningSoft: Color,
    val warningSoftForeground: Color,
    val border: Color,
    val default: Color,
    val scrollbar: Color,
    val segment: Color,
    val separator: Color,
    val fieldBackground: Color,
    val fieldBorder: Color,
    val backgroundSecondary: Color,
    val backgroundTertiary: Color,
)

private fun paletteModeTokens(
    background: Color,
    foreground: Color,
    muted: Color,
    overlay: Color,
    surface: Color,
    surfaceSecondary: Color,
    surfaceTertiary: Color,
    surfaceHover: Color,
    accent: Color,
    accentForeground: Color,
    accentSoft: Color,
    accentSoftForeground: Color,
    danger: Color,
    dangerForeground: Color,
    dangerSoft: Color,
    dangerSoftForeground: Color,
    success: Color,
    successForeground: Color,
    successSoft: Color,
    successSoftForeground: Color,
    warning: Color,
    warningForeground: Color,
    warningSoft: Color,
    warningSoftForeground: Color,
    border: Color,
    default: Color,
    scrollbar: Color,
    segment: Color,
    separator: Color,
    fieldBackground: Color,
    fieldBorder: Color,
    backgroundSecondary: Color,
    backgroundTertiary: Color,
): PaletteModeTokens {
    fun Color.opaque() = if (alpha < 1f) compositeOver(background).copy(alpha = 1f) else this
    return PaletteModeTokens(
        background = background.opaque(),
        foreground = foreground.opaque(),
        muted = muted.opaque(),
        overlay = overlay.opaque(),
        surface = surface.opaque(),
        surfaceSecondary = surfaceSecondary.opaque(),
        surfaceTertiary = surfaceTertiary.opaque(),
        surfaceHover = surfaceHover.opaque(),
        accent = accent.opaque(),
        accentForeground = accentForeground.opaque(),
        accentSoft = accentSoft.opaque(),
        accentSoftForeground = accentSoftForeground.opaque(),
        danger = danger.opaque(),
        dangerForeground = dangerForeground.opaque(),
        dangerSoft = dangerSoft.opaque(),
        dangerSoftForeground = dangerSoftForeground.opaque(),
        success = success.opaque(),
        successForeground = successForeground.opaque(),
        successSoft = successSoft.opaque(),
        successSoftForeground = successSoftForeground.opaque(),
        warning = warning.opaque(),
        warningForeground = warningForeground.opaque(),
        warningSoft = warningSoft.opaque(),
        warningSoftForeground = warningSoftForeground.opaque(),
        border = border.opaque(),
        default = default.opaque(),
        scrollbar = scrollbar.opaque(),
        segment = segment.opaque(),
        separator = separator.opaque(),
        fieldBackground = fieldBackground.opaque(),
        fieldBorder = fieldBorder.opaque(),
        backgroundSecondary = backgroundSecondary.opaque(),
        backgroundTertiary = backgroundTertiary.opaque(),
    )
}

private val HeroPalette.tokens: PaletteTokens
    get() = when (this) {
        HeroPalette.SURAU_BASE -> SurauBasePaletteTokens
        HeroPalette.DEFAULT -> DefaultPaletteTokens
        HeroPalette.MOUVE -> MouvePaletteTokens
        HeroPalette.SKY -> SkyPaletteTokens
        HeroPalette.MINT -> MintPaletteTokens
        HeroPalette.DISCORD -> DiscordPaletteTokens
        HeroPalette.UBER -> UberPaletteTokens
        HeroPalette.AIRBNB -> AirbnbPaletteTokens
    }

internal fun paletteName(palette: HeroPalette): String = palette.tokens.name

private fun PaletteModeTokens.semanticColors(): SurauSemanticColors = SurauSemanticColors(
    accent = accent,
    onAccent = accentForeground,
    accentSoft = accentSoft,
    default = default,
    background = background,
    surface = surface,
    surfaceSecondary = surfaceSecondary,
    surfaceTertiary = surfaceTertiary,
    surfaceHover = surfaceHover,
    overlay = overlay,
    fieldBackground = fieldBackground,
    fieldBorder = fieldBorder,
    border = border,
    separator = separator,
    muted = muted,
    scrollbar = scrollbar,
    segment = segment,
    success = success,
    onSuccess = successForeground,
    successContainer = successSoft,
    warning = warning,
    onWarning = warningForeground,
    warningContainer = warningSoft,
    danger = danger,
    onDanger = dangerForeground,
    dangerContainer = dangerSoft,
)

private fun PaletteModeTokens.colorScheme(dark: Boolean): ColorScheme {
    return if (dark) {
        darkColorScheme(
            primary = accent,
            onPrimary = accentForeground,
            primaryContainer = accentSoft,
            onPrimaryContainer = accentSoftForeground,
            inversePrimary = accent,
            secondary = accent,
            onSecondary = accentForeground,
            secondaryContainer = surfaceSecondary,
            onSecondaryContainer = foreground,
            tertiary = accent,
            onTertiary = accentForeground,
            tertiaryContainer = surfaceTertiary,
            onTertiaryContainer = foreground,
            error = danger,
            onError = dangerForeground,
            errorContainer = dangerSoft,
            onErrorContainer = dangerSoftForeground,
            background = background,
            onBackground = foreground,
            surface = surface,
            onSurface = foreground,
            surfaceVariant = surfaceSecondary,
            onSurfaceVariant = muted,
            surfaceContainerLowest = background,
            surfaceContainerLow = backgroundSecondary,
            surfaceContainer = surfaceSecondary,
            surfaceContainerHigh = surfaceTertiary,
            surfaceContainerHighest = separator,
            inverseSurface = foreground,
            inverseOnSurface = background,
            outline = border,
            outlineVariant = separator,
        )
    } else {
        lightColorScheme(
            primary = accent,
            onPrimary = accentForeground,
            primaryContainer = accentSoft,
            onPrimaryContainer = accentSoftForeground,
            inversePrimary = accent,
            secondary = accent,
            onSecondary = accentForeground,
            secondaryContainer = surfaceSecondary,
            onSecondaryContainer = foreground,
            tertiary = accent,
            onTertiary = accentForeground,
            tertiaryContainer = surfaceTertiary,
            onTertiaryContainer = foreground,
            error = danger,
            onError = dangerForeground,
            errorContainer = dangerSoft,
            onErrorContainer = dangerSoftForeground,
            background = background,
            onBackground = foreground,
            surface = surface,
            onSurface = foreground,
            surfaceVariant = surfaceSecondary,
            onSurfaceVariant = muted,
            surfaceContainerLowest = background,
            surfaceContainerLow = backgroundSecondary,
            surfaceContainer = surfaceSecondary,
            surfaceContainerHigh = surfaceTertiary,
            surfaceContainerHighest = separator,
            inverseSurface = foreground,
            inverseOnSurface = background,
            outline = border,
            outlineVariant = separator,
        )
    }
}

private val SurauBasePaletteTokens = PaletteTokens(
    name = "Surau Base",
    light = paletteModeTokens(
        background = Color(0xFFF4F4F0),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF5B5B4B),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF).copy(alpha = 0.8f),
        surfaceSecondary = Color(0xFFE8E8E3),
        surfaceTertiary = Color(0xFFEFEFEA),
        surfaceHover = Color(0xFF7E7E7E),
        accent = Color(0xFF4F772D),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF4F772D).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF3E592B),
        danger = Color(0xFFFF383C),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFFF383C).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFA43433),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF2B7745),
        warning = Color(0xFFF5A524),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF5A524).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF855F2E),
        border = Color(0xFFDEDED8),
        default = Color(0xFFE8E8E3),
        scrollbar = Color(0xFFD8D8D0),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFE5E5E0),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFDEDED8),
        backgroundSecondary = Color(0xFFEAEAE6),
        backgroundTertiary = Color(0xFFE0E0DD),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF151510),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFFABAB9C),
        overlay = Color(0xFF191912),
        surface = Color(0xFF1D1D16),
        surfaceSecondary = Color(0xFF212119),
        surfaceTertiary = Color(0xFF26261D),
        surfaceHover = Color(0xFF2C2C25),
        accent = Color(0xFF6A994E),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF6A994E).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFF91B47E),
        danger = Color(0xFFDB3B3E),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDB3B3E).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFEB7872),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF74D88F),
        warning = Color(0xFFF7B750),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF7B750).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFF9CB86),
        border = Color(0xFF313127),
        default = Color(0xFF2B2B22),
        scrollbar = Color(0xFFABAB9C),
        segment = Color(0xFF49493C),
        separator = Color(0xFF25251D),
        fieldBackground = Color(0xFF191912),
        fieldBorder = Color(0xFF313127),
        backgroundSecondary = Color(0xFF1C1C17),
        backgroundTertiary = Color(0xFF24241F),
    ),
)

private val DefaultPaletteTokens = PaletteTokens(
    name = "Default",
    light = paletteModeTokens(
        background = Color(0xFFF5F5F5),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF727272),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFEFEFEF),
        surfaceTertiary = Color(0xFFEAEAEA),
        surfaceHover = Color(0xFFEAEAEA),
        accent = Color(0xFF0485F7),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF0485F7).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF1E63AE),
        danger = Color(0xFFFF383C),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFFF383C).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFA43433),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF2B7745),
        warning = Color(0xFFF5A524),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF5A524).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF855F2E),
        border = Color(0xFFDEDEDE),
        default = Color(0xFFEBEBEB),
        scrollbar = Color(0xFFD4D4D4),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFE4E4E4),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFDEDEDE),
        backgroundSecondary = Color(0xFFEBEBEB),
        backgroundTertiary = Color(0xFFE1E1E1),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF060606),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFFA0A0A0),
        overlay = Color(0xFF181818),
        surface = Color(0xFF181818),
        surfaceSecondary = Color(0xFF232323),
        surfaceTertiary = Color(0xFF272727),
        surfaceHover = Color(0xFF272727),
        accent = Color(0xFF0485F7),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF0485F7).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFF61A8FC),
        danger = Color(0xFFDB3B3E),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDB3B3E).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFEB7872),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF74D88F),
        warning = Color(0xFFF7B750),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF7B750).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFF9CB86),
        border = Color(0xFF292929),
        default = Color(0xFF272727),
        scrollbar = Color(0xFFA0A0A0),
        segment = Color(0xFF474747),
        separator = Color(0xFF222222),
        fieldBackground = Color(0xFF181818),
        fieldBorder = Color(0xFF292929),
        backgroundSecondary = Color(0xFF0D0D0D),
        backgroundTertiary = Color(0xFF141414),
    ),
)

private val MouvePaletteTokens = PaletteTokens(
    name = "Mouve",
    light = paletteModeTokens(
        background = Color(0xFFF1EEF7),
        foreground = Color(0xFF23202A),
        muted = Color(0xFF7D778A),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFEFEDF6),
        surfaceTertiary = Color(0xFFEBE7F3),
        surfaceHover = Color(0xFFE4E3E8),
        accent = Color(0xFF8451C9),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF8451C9).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF654396),
        danger = Color(0xFFFF383C),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFFF383C).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFAA383B),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF23202A),
        successSoft = Color(0xFF17C964).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF327C4E),
        warning = Color(0xFFF5A524),
        warningForeground = Color(0xFF23202A),
        warningSoft = Color(0xFFF5A524).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF8B6438),
        border = Color(0xFFD9D5E0),
        default = Color(0xFFE6E3EC),
        scrollbar = Color(0xFFC6C1CF),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFE5E3EA),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFD9D5E3),
        backgroundSecondary = Color(0xFFE8E5EE),
        backgroundTertiary = Color(0xFFDEDBE5),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF0F0B15),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFF918D9A),
        overlay = Color(0xFF17141E),
        surface = Color(0xFF17141E),
        surfaceSecondary = Color(0xFF211D27),
        surfaceTertiary = Color(0xFF28242F),
        surfaceHover = Color(0xFF26232D),
        accent = Color(0xFFAE84F2),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFFAE84F2).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFFC2A6F7),
        danger = Color(0xFFDB3B3E),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDB3B3E).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFEB7872),
        success = Color(0xFF17C964),
        successForeground = Color(0xFFE5E3EA),
        successSoft = Color(0xFF17C964).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF74D88F),
        warning = Color(0xFFF7B750),
        warningForeground = Color(0xFFE5E3EA),
        warningSoft = Color(0xFFF7B750).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFF9CB86),
        border = Color(0xFF2F2C37),
        default = Color(0xFF25222C),
        scrollbar = Color(0xFF3C3844),
        segment = Color(0xFF2B2634),
        separator = Color(0xFF2A2731),
        fieldBackground = Color(0xFF1C1922),
        fieldBorder = Color(0xFF35303E),
        backgroundSecondary = Color(0xFF16121C),
        backgroundTertiary = Color(0xFF1E1A24),
    ),
)

private val SkyPaletteTokens = PaletteTokens(
    name = "Sky",
    light = paletteModeTokens(
        background = Color(0xFFECF7FE),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF617681),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFE1F3FC),
        surfaceTertiary = Color(0xFFDCEDF7),
        surfaceHover = Color(0xFFEAEAEA),
        accent = Color(0xFF7DD3FC),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF7DD3FC).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF5E95B1),
        danger = Color(0xFFFF383C),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFFF383C).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFA43433),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF2B7745),
        warning = Color(0xFFF5A524),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF5A524).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF855F2E),
        border = Color(0xFFD5E0E6),
        default = Color(0xFFE2EDF3),
        scrollbar = Color(0xFFCBD7DD),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFDBE7ED),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFD5E0E6),
        backgroundSecondary = Color(0xFFE2EDF4),
        backgroundTertiary = Color(0xFFD9E3E9),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF02070A),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFF8EA4AF),
        overlay = Color(0xFF081B24),
        surface = Color(0xFF081B24),
        surfaceSecondary = Color(0xFF18252C),
        surfaceTertiary = Color(0xFF1B2930),
        surfaceHover = Color(0xFF192A33),
        accent = Color(0xFF7DD3FC),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF7DD3FC).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFFA3DFFD),
        danger = Color(0xFFDB3B3E),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDB3B3E).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFEB7872),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF74D88F),
        warning = Color(0xFFF7B750),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF7B750).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFF9CB86),
        border = Color(0xFF212A2F),
        default = Color(0xFF20292D),
        scrollbar = Color(0xFF97A2A8),
        segment = Color(0xFF3F484D),
        separator = Color(0xFF1A2328),
        fieldBackground = Color(0xFF081B24),
        fieldBorder = Color(0xFF212A2F),
        backgroundSecondary = Color(0xFF060E11),
        backgroundTertiary = Color(0xFF0E1619),
    ),
)

private val MintPaletteTokens = PaletteTokens(
    name = "Mint",
    light = paletteModeTokens(
        background = Color(0xFFEEF8F1),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF65786A),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFE4F4E9),
        surfaceTertiary = Color(0xFFDFEFE4),
        surfaceHover = Color(0xFFEAEAEA),
        accent = Color(0xFF86EFAC),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF86EFAC).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF64A77D),
        danger = Color(0xFFFF383C),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFFF383C).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFA43433),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF2B7745),
        warning = Color(0xFFF5A524),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF5A524).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF855F2E),
        border = Color(0xFFD7E1DA),
        default = Color(0xFFE4EEE7),
        scrollbar = Color(0xFFCDD8D0),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFDDE8E0),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFD7E1DA),
        backgroundSecondary = Color(0xFFE4EEE7),
        backgroundTertiary = Color(0xFFDAE4DE),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF030704),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFF92A698),
        overlay = Color(0xFF0D1C12),
        surface = Color(0xFF0D1C12),
        surfaceSecondary = Color(0xFF1B271E),
        surfaceTertiary = Color(0xFF1E2A22),
        surfaceHover = Color(0xFF1D2B21),
        accent = Color(0xFF86EFAC),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF86EFAC).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFFAAF3C2),
        danger = Color(0xFFDB3B3E),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDB3B3E).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFEB7872),
        success = Color(0xFF17C964),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF17C964).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF74D88F),
        warning = Color(0xFFF7B750),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFF7B750).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFF9CB86),
        border = Color(0xFF232B26),
        default = Color(0xFF222A24),
        scrollbar = Color(0xFF99A39C),
        segment = Color(0xFF414943),
        separator = Color(0xFF1C241E),
        fieldBackground = Color(0xFF0D1C12),
        fieldBorder = Color(0xFF232B26),
        backgroundSecondary = Color(0xFF080E09),
        backgroundTertiary = Color(0xFF0F1511),
    ),
)

private val DiscordPaletteTokens = PaletteTokens(
    name = "Discord",
    light = paletteModeTokens(
        background = Color(0xFFF3F5FC),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF6E717E),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFECEFFA),
        surfaceTertiary = Color(0xFFE7EAF5),
        surfaceHover = Color(0xFFEAEAEA),
        accent = Color(0xFF5865F2),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF5865F2).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF434EAB),
        danger = Color(0xFFDA373C),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDA373C).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFF8F3232),
        success = Color(0xFF248046),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF248046).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF255134),
        warning = Color(0xFFFEE75C),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFFEE75C).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF897E43),
        border = Color(0xFFDCDEE5),
        default = Color(0xFFE9EBF2),
        scrollbar = Color(0xFFD2D4DB),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFE2E4EB),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFDCDEE5),
        backgroundSecondary = Color(0xFFE9EBF2),
        backgroundTertiary = Color(0xFFDFE1E8),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF050609),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFF9C9FAD),
        overlay = Color(0xFF151822),
        surface = Color(0xFF151822),
        surfaceSecondary = Color(0xFF21232B),
        surfaceTertiary = Color(0xFF24272E),
        surfaceHover = Color(0xFF242731),
        accent = Color(0xFF5865F2),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF5865F2).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFF7F92F9),
        danger = Color(0xFFED4245),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFED4245).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFF87E77),
        success = Color(0xFF57F287),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF57F287).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF91F6A9),
        warning = Color(0xFFFEE75C),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFFEE75C).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFFDEE92),
        border = Color(0xFF27292E),
        default = Color(0xFF26272C),
        scrollbar = Color(0xFF9EA0A6),
        segment = Color(0xFF45464C),
        separator = Color(0xFF202127),
        fieldBackground = Color(0xFF151822),
        fieldBorder = Color(0xFF27292E),
        backgroundSecondary = Color(0xFF0B0D10),
        backgroundTertiary = Color(0xFF131418),
    ),
)

private val UberPaletteTokens = PaletteTokens(
    name = "Uber",
    light = paletteModeTokens(
        background = Color(0xFFF5F5F5),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF727272),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFEFEFEF),
        surfaceTertiary = Color(0xFFEAEAEA),
        surfaceHover = Color(0xFFEAEAEA),
        accent = Color(0xFF000000),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFF000000).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFF010101),
        danger = Color(0xFFDE1135),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFDE1135).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFF91252E),
        success = Color(0xFF05A357),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF05A357).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF24633E),
        warning = Color(0xFFFFC043),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFFFC043).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF896C38),
        border = Color(0xFFDEDEDE),
        default = Color(0xFFEBEBEB),
        scrollbar = Color(0xFFD4D4D4),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFE4E4E4),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFDEDEDE),
        backgroundSecondary = Color(0xFFEBEBEB),
        backgroundTertiary = Color(0xFFE1E1E1),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF060606),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFFA0A0A0),
        overlay = Color(0xFF181818),
        surface = Color(0xFF181818),
        surfaceSecondary = Color(0xFF232323),
        surfaceTertiary = Color(0xFF272727),
        surfaceHover = Color(0xFF272727),
        accent = Color(0xFFFAFAFA),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFFFAFAFA).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFFFBFBFB),
        danger = Color(0xFFFF6666),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFFF6666).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFFF938F),
        success = Color(0xFF3AA76D),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF3AA76D).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF77BF93),
        warning = Color(0xFFFFD166),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFFFD166).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFFFDD95),
        border = Color(0xFF292929),
        default = Color(0xFF272727),
        scrollbar = Color(0xFFA0A0A0),
        segment = Color(0xFF474747),
        separator = Color(0xFF222222),
        fieldBackground = Color(0xFF181818),
        fieldBorder = Color(0xFF292929),
        backgroundSecondary = Color(0xFF0D0D0D),
        backgroundTertiary = Color(0xFF141414),
    ),
)

private val AirbnbPaletteTokens = PaletteTokens(
    name = "Airbnb",
    light = paletteModeTokens(
        background = Color(0xFFF5F5F5),
        foreground = Color(0xFF18181B),
        muted = Color(0xFF727272),
        overlay = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceSecondary = Color(0xFFEFEFEF),
        surfaceTertiary = Color(0xFFEAEAEA),
        surfaceHover = Color(0xFFEAEAEA),
        accent = Color(0xFFFF385C),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFFFF385C).copy(alpha = 0.15f),
        accentSoftForeground = Color(0xFFB43648),
        danger = Color(0xFFC13515),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFC13515).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFF802F20),
        success = Color(0xFF008489),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF008489).copy(alpha = 0.15f),
        successSoftForeground = Color(0xFF1F5357),
        warning = Color(0xFFFC642D),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFFC642D).copy(alpha = 0.15f),
        warningSoftForeground = Color(0xFF8A422C),
        border = Color(0xFFDEDEDE),
        default = Color(0xFFEBEBEB),
        scrollbar = Color(0xFFD4D4D4),
        segment = Color(0xFFFFFFFF),
        separator = Color(0xFFE4E4E4),
        fieldBackground = Color(0xFFFFFFFF),
        fieldBorder = Color(0xFFDEDEDE),
        backgroundSecondary = Color(0xFFEBEBEB),
        backgroundTertiary = Color(0xFFE1E1E1),
    ),
    dark = paletteModeTokens(
        background = Color(0xFF060606),
        foreground = Color(0xFFFCFCFC),
        muted = Color(0xFFA0A0A0),
        overlay = Color(0xFF181818),
        surface = Color(0xFF181818),
        surfaceSecondary = Color(0xFF232323),
        surfaceTertiary = Color(0xFF272727),
        surfaceHover = Color(0xFF272727),
        accent = Color(0xFFFF385C),
        accentForeground = Color(0xFFFCFCFC),
        accentSoft = Color(0xFFFF385C).copy(alpha = 0.12f),
        accentSoftForeground = Color(0xFFFF7B87),
        danger = Color(0xFFC13515),
        dangerForeground = Color(0xFFFCFCFC),
        dangerSoft = Color(0xFFC13515).copy(alpha = 0.15f),
        dangerSoftForeground = Color(0xFFD7725B),
        success = Color(0xFF00A699),
        successForeground = Color(0xFF18181B),
        successSoft = Color(0xFF00A699).copy(alpha = 0.12f),
        successSoftForeground = Color(0xFF6ABEB3),
        warning = Color(0xFFFFB400),
        warningForeground = Color(0xFF18181B),
        warningSoft = Color(0xFFFFB400).copy(alpha = 0.12f),
        warningSoftForeground = Color(0xFFFFC96F),
        border = Color(0xFF292929),
        default = Color(0xFF272727),
        scrollbar = Color(0xFFA0A0A0),
        segment = Color(0xFF474747),
        separator = Color(0xFF222222),
        fieldBackground = Color(0xFF181818),
        fieldBorder = Color(0xFF292929),
        backgroundSecondary = Color(0xFF0D0D0D),
        backgroundTertiary = Color(0xFF141414),
    ),
)

internal val DefaultLightSemanticColors = DefaultPaletteTokens.light.semanticColors()
internal val DefaultDarkSemanticColors = DefaultPaletteTokens.dark.semanticColors()
internal val DefaultLightColorScheme = DefaultPaletteTokens.light.colorScheme(dark = false)
internal val DefaultDarkColorScheme = DefaultPaletteTokens.dark.colorScheme(dark = true)

internal val SurauBaseLightSemanticColors = SurauBasePaletteTokens.light.semanticColors()
internal val SurauBaseDarkSemanticColors = SurauBasePaletteTokens.dark.semanticColors()
internal val SurauBaseLightColorScheme = SurauBasePaletteTokens.light.colorScheme(dark = false)
internal val SurauBaseDarkColorScheme = SurauBasePaletteTokens.dark.colorScheme(dark = true)

/** The extended semantic colors for [palette] in the given mode. */
internal fun paletteSemanticColors(palette: HeroPalette, dark: Boolean): SurauSemanticColors =
    if (dark) palette.tokens.dark.semanticColors() else palette.tokens.light.semanticColors()

/** The Material 3 color scheme for [palette] in the given mode. */
internal fun paletteColorScheme(palette: HeroPalette, dark: Boolean): ColorScheme =
    if (dark) palette.tokens.dark.colorScheme(dark = true) else palette.tokens.light.colorScheme(dark = false)
