/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.surau.app.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * A named, hand-tuned HeroUI design-token palette. [DEFAULT] (a balanced neutral grey + blue accent)
 * is the app's baseline; the others are alternative accents over the same balanced neutrals.
 */
enum class HeroPalette {
    DEFAULT,
    MOUVE,
    SKY,
}

// ---------------- Default ----------------
internal val DefaultLightSemanticColors = SurauSemanticColors(
    accent = Color(0xFF0485F7),
    onAccent = Color(0xFFFCFCFC),
    accentSoft = Color(0xFFD1E4F5),
    default = Color(0xFFEBEBEB),
    background = Color(0xFFF5F5F5),
    surface = Color(0xFFFFFFFF),
    surfaceSecondary = Color(0xFFEFEFEF),
    surfaceTertiary = Color(0xFFEAEAEA),
    surfaceHover = Color(0xFFEAEAEA),
    overlay = Color(0xFFFFFFFF),
    fieldBackground = Color(0xFFFFFFFF),
    fieldBorder = Color(0xFFDEDEDE),
    border = Color(0xFFDEDEDE),
    separator = Color(0xFFE4E4E4),
    muted = Color(0xFF727272),
    scrollbar = Color(0xFFD4D4D4),
    segment = Color(0xFFFFFFFF),
    success = Color(0xFF17C964),
    onSuccess = Color(0xFF18181B),
    successContainer = Color(0xFFD4EEDF),
    warning = Color(0xFFF5A524),
    onWarning = Color(0xFF18181B),
    warningContainer = Color(0xFFF5E9D6),
    danger = Color(0xFFFF383C),
    onDanger = Color(0xFFFCFCFC),
    dangerContainer = Color(0xFFF6D9D9),
)
internal val DefaultDarkSemanticColors = SurauSemanticColors(
    accent = Color(0xFF0485F7),
    onAccent = Color(0xFFFCFCFC),
    accentSoft = Color(0xFF061523),
    default = Color(0xFF272727),
    background = Color(0xFF060606),
    surface = Color(0xFF181818),
    surfaceSecondary = Color(0xFF232323),
    surfaceTertiary = Color(0xFF272727),
    surfaceHover = Color(0xFF272727),
    overlay = Color(0xFF181818),
    fieldBackground = Color(0xFF181818),
    fieldBorder = Color(0xFF292929),
    border = Color(0xFF292929),
    separator = Color(0xFF222222),
    muted = Color(0xFFA0A0A0),
    scrollbar = Color(0xFFA0A0A0),
    segment = Color(0xFF474747),
    success = Color(0xFF17C964),
    onSuccess = Color(0xFF18181B),
    successContainer = Color(0xFF081D11),
    warning = Color(0xFFF7B750),
    onWarning = Color(0xFF18181B),
    warningContainer = Color(0xFF231B0F),
    danger = Color(0xFFDB3B3E),
    onDanger = Color(0xFFFCFCFC),
    dangerContainer = Color(0xFF260E0E),
)
internal val DefaultLightColorScheme = lightColorScheme(
    primary = Color(0xFF0485F7),
    onPrimary = Color(0xFFFCFCFC),
    primaryContainer = Color(0xFFD1E4F5),
    onPrimaryContainer = Color(0xFF1E63AE),
    inversePrimary = Color(0xFF0485F7),
    secondary = Color(0xFF0485F7),
    onSecondary = Color(0xFFFCFCFC),
    secondaryContainer = Color(0xFFEFEFEF),
    onSecondaryContainer = Color(0xFF18181B),
    tertiary = Color(0xFF0485F7),
    onTertiary = Color(0xFFFCFCFC),
    tertiaryContainer = Color(0xFFEAEAEA),
    onTertiaryContainer = Color(0xFF18181B),
    error = Color(0xFFFF383C),
    onError = Color(0xFFFCFCFC),
    errorContainer = Color(0xFFF6D9D9),
    onErrorContainer = Color(0xFFA43433),
    background = Color(0xFFF5F5F5),
    onBackground = Color(0xFF18181B),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF18181B),
    surfaceVariant = Color(0xFFEFEFEF),
    onSurfaceVariant = Color(0xFF727272),
    surfaceContainerLowest = Color(0xFFF5F5F5),
    surfaceContainerLow = Color(0xFFEBEBEB),
    surfaceContainer = Color(0xFFEFEFEF),
    surfaceContainerHigh = Color(0xFFEAEAEA),
    surfaceContainerHighest = Color(0xFFE4E4E4),
    inverseSurface = Color(0xFF18181B),
    inverseOnSurface = Color(0xFFF5F5F5),
    outline = Color(0xFFDEDEDE),
    outlineVariant = Color(0xFFE4E4E4),
)
internal val DefaultDarkColorScheme = darkColorScheme(
    primary = Color(0xFF0485F7),
    onPrimary = Color(0xFFFCFCFC),
    primaryContainer = Color(0xFF061523),
    onPrimaryContainer = Color(0xFF61A8FC),
    inversePrimary = Color(0xFF0485F7),
    secondary = Color(0xFF0485F7),
    onSecondary = Color(0xFFFCFCFC),
    secondaryContainer = Color(0xFF232323),
    onSecondaryContainer = Color(0xFFFCFCFC),
    tertiary = Color(0xFF0485F7),
    onTertiary = Color(0xFFFCFCFC),
    tertiaryContainer = Color(0xFF272727),
    onTertiaryContainer = Color(0xFFFCFCFC),
    error = Color(0xFFDB3B3E),
    onError = Color(0xFFFCFCFC),
    errorContainer = Color(0xFF260E0E),
    onErrorContainer = Color(0xFFEB7872),
    background = Color(0xFF060606),
    onBackground = Color(0xFFFCFCFC),
    surface = Color(0xFF181818),
    onSurface = Color(0xFFFCFCFC),
    surfaceVariant = Color(0xFF232323),
    onSurfaceVariant = Color(0xFFA0A0A0),
    surfaceContainerLowest = Color(0xFF060606),
    surfaceContainerLow = Color(0xFF0D0D0D),
    surfaceContainer = Color(0xFF232323),
    surfaceContainerHigh = Color(0xFF272727),
    surfaceContainerHighest = Color(0xFF222222),
    inverseSurface = Color(0xFFFCFCFC),
    inverseOnSurface = Color(0xFF060606),
    outline = Color(0xFF292929),
    outlineVariant = Color(0xFF222222),
)

// ---------------- Mouve ----------------
internal val MouveLightSemanticColors = SurauSemanticColors(
    accent = Color(0xFF8451C9),
    onAccent = Color(0xFFFCFCFC),
    accentSoft = Color(0xFFE1D6F0),
    default = Color(0xFFE6E3EC),
    background = Color(0xFFF1EEF7),
    surface = Color(0xFFFFFFFF),
    surfaceSecondary = Color(0xFFEFEDF6),
    surfaceTertiary = Color(0xFFEBE7F3),
    surfaceHover = Color(0xFFE4E3E8),
    overlay = Color(0xFFFFFFFF),
    fieldBackground = Color(0xFFFFFFFF),
    fieldBorder = Color(0xFFD9D5E3),
    border = Color(0xFFD9D5E0),
    separator = Color(0xFFE5E3EA),
    muted = Color(0xFF7D778A),
    scrollbar = Color(0xFFC6C1CF),
    segment = Color(0xFFFFFFFF),
    success = Color(0xFF17C964),
    onSuccess = Color(0xFF23202A),
    successContainer = Color(0xFFD0E8E1),
    warning = Color(0xFFF5A524),
    onWarning = Color(0xFF23202A),
    warningContainer = Color(0xFFF2E3D7),
    danger = Color(0xFFFF383C),
    onDanger = Color(0xFFFCFCFC),
    dangerContainer = Color(0xFFF3D3DB),
)
internal val MouveDarkSemanticColors = SurauSemanticColors(
    accent = Color(0xFFAE84F2),
    onAccent = Color(0xFFFCFCFC),
    accentSoft = Color(0xFF221A30),
    default = Color(0xFF25222C),
    background = Color(0xFF0F0B15),
    surface = Color(0xFF17141E),
    surfaceSecondary = Color(0xFF211D27),
    surfaceTertiary = Color(0xFF28242F),
    surfaceHover = Color(0xFF26232D),
    overlay = Color(0xFF17141E),
    fieldBackground = Color(0xFF1C1922),
    fieldBorder = Color(0xFF35303E),
    border = Color(0xFF2F2C37),
    separator = Color(0xFF2A2731),
    muted = Color(0xFF918D9A),
    scrollbar = Color(0xFF3C3844),
    segment = Color(0xFF2B2634),
    success = Color(0xFF17C964),
    onSuccess = Color(0xFFE5E3EA),
    successContainer = Color(0xFF10221E),
    warning = Color(0xFFF7B750),
    onWarning = Color(0xFFE5E3EA),
    warningContainer = Color(0xFF2B201C),
    danger = Color(0xFFDB3B3E),
    onDanger = Color(0xFFFCFCFC),
    dangerContainer = Color(0xFF2E121B),
)
internal val MouveLightColorScheme = lightColorScheme(
    primary = Color(0xFF8451C9),
    onPrimary = Color(0xFFFCFCFC),
    primaryContainer = Color(0xFFE1D6F0),
    onPrimaryContainer = Color(0xFF654396),
    inversePrimary = Color(0xFF8451C9),
    secondary = Color(0xFF8451C9),
    onSecondary = Color(0xFFFCFCFC),
    secondaryContainer = Color(0xFFEFEDF6),
    onSecondaryContainer = Color(0xFF23202A),
    tertiary = Color(0xFF8451C9),
    onTertiary = Color(0xFFFCFCFC),
    tertiaryContainer = Color(0xFFEBE7F3),
    onTertiaryContainer = Color(0xFF23202A),
    error = Color(0xFFFF383C),
    onError = Color(0xFFFCFCFC),
    errorContainer = Color(0xFFF3D3DB),
    onErrorContainer = Color(0xFFAA383B),
    background = Color(0xFFF1EEF7),
    onBackground = Color(0xFF23202A),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF23202A),
    surfaceVariant = Color(0xFFEFEDF6),
    onSurfaceVariant = Color(0xFF7D778A),
    surfaceContainerLowest = Color(0xFFF1EEF7),
    surfaceContainerLow = Color(0xFFE8E5EE),
    surfaceContainer = Color(0xFFEFEDF6),
    surfaceContainerHigh = Color(0xFFEBE7F3),
    surfaceContainerHighest = Color(0xFFE5E3EA),
    inverseSurface = Color(0xFF23202A),
    inverseOnSurface = Color(0xFFF1EEF7),
    outline = Color(0xFFD9D5E0),
    outlineVariant = Color(0xFFE5E3EA),
)
internal val MouveDarkColorScheme = darkColorScheme(
    primary = Color(0xFFAE84F2),
    onPrimary = Color(0xFFFCFCFC),
    primaryContainer = Color(0xFF221A30),
    onPrimaryContainer = Color(0xFFC2A6F7),
    inversePrimary = Color(0xFFAE84F2),
    secondary = Color(0xFFAE84F2),
    onSecondary = Color(0xFFFCFCFC),
    secondaryContainer = Color(0xFF211D27),
    onSecondaryContainer = Color(0xFFFCFCFC),
    tertiary = Color(0xFFAE84F2),
    onTertiary = Color(0xFFFCFCFC),
    tertiaryContainer = Color(0xFF28242F),
    onTertiaryContainer = Color(0xFFFCFCFC),
    error = Color(0xFFDB3B3E),
    onError = Color(0xFFFCFCFC),
    errorContainer = Color(0xFF2E121B),
    onErrorContainer = Color(0xFFEB7872),
    background = Color(0xFF0F0B15),
    onBackground = Color(0xFFFCFCFC),
    surface = Color(0xFF17141E),
    onSurface = Color(0xFFFCFCFC),
    surfaceVariant = Color(0xFF211D27),
    onSurfaceVariant = Color(0xFF918D9A),
    surfaceContainerLowest = Color(0xFF0F0B15),
    surfaceContainerLow = Color(0xFF16121C),
    surfaceContainer = Color(0xFF211D27),
    surfaceContainerHigh = Color(0xFF28242F),
    surfaceContainerHighest = Color(0xFF2A2731),
    inverseSurface = Color(0xFFFCFCFC),
    inverseOnSurface = Color(0xFF0F0B15),
    outline = Color(0xFF2F2C37),
    outlineVariant = Color(0xFF2A2731),
)

// ---------------- Sky ----------------
internal val SkyLightSemanticColors = SurauSemanticColors(
    accent = Color(0xFF7DD3FC),
    onAccent = Color(0xFFFCFCFC),
    accentSoft = Color(0xFFDBF2FE),
    default = Color(0xFFE2EDF3),
    background = Color(0xFFECF7FE),
    surface = Color(0xFFFFFFFF),
    surfaceSecondary = Color(0xFFE1F3FC),
    surfaceTertiary = Color(0xFFDCEDF7),
    surfaceHover = Color(0xFFEAEAEA),
    overlay = Color(0xFFFFFFFF),
    fieldBackground = Color(0xFFFFFFFF),
    fieldBorder = Color(0xFFD5E0E6),
    border = Color(0xFFD5E0E6),
    separator = Color(0xFFDBE7ED),
    muted = Color(0xFF617681),
    scrollbar = Color(0xFFCBD7DD),
    segment = Color(0xFFFFFFFF),
    success = Color(0xFF17C964),
    onSuccess = Color(0xFF18181B),
    successContainer = Color(0xFFCCF0E7),
    warning = Color(0xFFF5A524),
    onWarning = Color(0xFF18181B),
    warningContainer = Color(0xFFEDEBDD),
    danger = Color(0xFFFF383C),
    onDanger = Color(0xFFFCFCFC),
    dangerContainer = Color(0xFFEFDAE1),
)
internal val SkyDarkSemanticColors = SurauSemanticColors(
    accent = Color(0xFF7DD3FC),
    onAccent = Color(0xFFFCFCFC),
    accentSoft = Color(0xFF111F27),
    default = Color(0xFF20292D),
    background = Color(0xFF02070A),
    surface = Color(0xFF081B24),
    surfaceSecondary = Color(0xFF18252C),
    surfaceTertiary = Color(0xFF1B2930),
    surfaceHover = Color(0xFF192A33),
    overlay = Color(0xFF081B24),
    fieldBackground = Color(0xFF081B24),
    fieldBorder = Color(0xFF212A2F),
    border = Color(0xFF212A2F),
    separator = Color(0xFF1A2328),
    muted = Color(0xFF8EA4AF),
    scrollbar = Color(0xFF97A2A8),
    segment = Color(0xFF3F484D),
    success = Color(0xFF17C964),
    onSuccess = Color(0xFF18181B),
    successContainer = Color(0xFF051E15),
    warning = Color(0xFFF7B750),
    onWarning = Color(0xFF18181B),
    warningContainer = Color(0xFF1F1C12),
    danger = Color(0xFFDB3B3E),
    onDanger = Color(0xFFFCFCFC),
    dangerContainer = Color(0xFF230F12),
)
internal val SkyLightColorScheme = lightColorScheme(
    primary = Color(0xFF7DD3FC),
    onPrimary = Color(0xFFFCFCFC),
    primaryContainer = Color(0xFFDBF2FE),
    onPrimaryContainer = Color(0xFF5E95B1),
    inversePrimary = Color(0xFF7DD3FC),
    secondary = Color(0xFF7DD3FC),
    onSecondary = Color(0xFFFCFCFC),
    secondaryContainer = Color(0xFFE1F3FC),
    onSecondaryContainer = Color(0xFF18181B),
    tertiary = Color(0xFF7DD3FC),
    onTertiary = Color(0xFFFCFCFC),
    tertiaryContainer = Color(0xFFDCEDF7),
    onTertiaryContainer = Color(0xFF18181B),
    error = Color(0xFFFF383C),
    onError = Color(0xFFFCFCFC),
    errorContainer = Color(0xFFEFDAE1),
    onErrorContainer = Color(0xFFA43433),
    background = Color(0xFFECF7FE),
    onBackground = Color(0xFF18181B),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF18181B),
    surfaceVariant = Color(0xFFE1F3FC),
    onSurfaceVariant = Color(0xFF617681),
    surfaceContainerLowest = Color(0xFFECF7FE),
    surfaceContainerLow = Color(0xFFE2EDF4),
    surfaceContainer = Color(0xFFE1F3FC),
    surfaceContainerHigh = Color(0xFFDCEDF7),
    surfaceContainerHighest = Color(0xFFDBE7ED),
    inverseSurface = Color(0xFF18181B),
    inverseOnSurface = Color(0xFFECF7FE),
    outline = Color(0xFFD5E0E6),
    outlineVariant = Color(0xFFDBE7ED),
)
internal val SkyDarkColorScheme = darkColorScheme(
    primary = Color(0xFF7DD3FC),
    onPrimary = Color(0xFFFCFCFC),
    primaryContainer = Color(0xFF111F27),
    onPrimaryContainer = Color(0xFFA3DFFD),
    inversePrimary = Color(0xFF7DD3FC),
    secondary = Color(0xFF7DD3FC),
    onSecondary = Color(0xFFFCFCFC),
    secondaryContainer = Color(0xFF18252C),
    onSecondaryContainer = Color(0xFFFCFCFC),
    tertiary = Color(0xFF7DD3FC),
    onTertiary = Color(0xFFFCFCFC),
    tertiaryContainer = Color(0xFF1B2930),
    onTertiaryContainer = Color(0xFFFCFCFC),
    error = Color(0xFFDB3B3E),
    onError = Color(0xFFFCFCFC),
    errorContainer = Color(0xFF230F12),
    onErrorContainer = Color(0xFFEB7872),
    background = Color(0xFF02070A),
    onBackground = Color(0xFFFCFCFC),
    surface = Color(0xFF081B24),
    onSurface = Color(0xFFFCFCFC),
    surfaceVariant = Color(0xFF18252C),
    onSurfaceVariant = Color(0xFF8EA4AF),
    surfaceContainerLowest = Color(0xFF02070A),
    surfaceContainerLow = Color(0xFF060E11),
    surfaceContainer = Color(0xFF18252C),
    surfaceContainerHigh = Color(0xFF1B2930),
    surfaceContainerHighest = Color(0xFF1A2328),
    inverseSurface = Color(0xFFFCFCFC),
    inverseOnSurface = Color(0xFF02070A),
    outline = Color(0xFF212A2F),
    outlineVariant = Color(0xFF1A2328),
)

/** The extended semantic colors for [palette] in the given mode. */
internal fun paletteSemanticColors(palette: HeroPalette, dark: Boolean): SurauSemanticColors =
    when (palette) {
        HeroPalette.DEFAULT -> if (dark) DefaultDarkSemanticColors else DefaultLightSemanticColors
        HeroPalette.MOUVE -> if (dark) MouveDarkSemanticColors else MouveLightSemanticColors
        HeroPalette.SKY -> if (dark) SkyDarkSemanticColors else SkyLightSemanticColors
    }

/** The Material 3 color scheme for [palette] in the given mode. */
internal fun paletteColorScheme(palette: HeroPalette, dark: Boolean): ColorScheme =
    when (palette) {
        HeroPalette.DEFAULT -> if (dark) DefaultDarkColorScheme else DefaultLightColorScheme
        HeroPalette.MOUVE -> if (dark) MouveDarkColorScheme else MouveLightColorScheme
        HeroPalette.SKY -> if (dark) SkyDarkColorScheme else SkyLightColorScheme
    }
