/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.surau.app.core.database.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.datetime.Instant
import org.surau.app.core.model.data.quran.AyahKey
import org.surau.app.core.model.data.quran.Bookmark

/**
 * A saved Quran ayah. Multi-row, keyed by an autogenerated local [id] with a unique index on
 * [ayahKey] (one bookmark per ayah — this makes the backend's upsert-by-target safe). [surahId] is
 * denormalized from [ayahKey] so the list can group/filter by surah without parsing strings in SQL.
 *
 * [serverId] is the backend SavedItem UUID; [pendingSync]/[pendingDelete] drive offline-first sync.
 */
@Entity(
    tableName = "bookmarks",
    indices = [Index(value = ["ayah_key"], unique = true)],
)
data class BookmarkEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    @ColumnInfo(name = "ayah_key")
    val ayahKey: String,
    @ColumnInfo(name = "surah_id")
    val surahId: Int,
    @ColumnInfo(name = "label")
    val label: String?,
    @ColumnInfo(name = "note")
    val note: String?,
    @ColumnInfo(name = "tags")
    val tags: List<String>,
    @ColumnInfo(name = "created_at")
    val createdAt: Instant,
    @ColumnInfo(name = "updated_at")
    val updatedAt: Instant,
    @ColumnInfo(name = "server_id")
    val serverId: String?,
    @ColumnInfo(name = "pending_sync")
    val pendingSync: Boolean,
    @ColumnInfo(name = "pending_delete")
    val pendingDelete: Boolean,
)

fun BookmarkEntity.asExternalModel() = Bookmark(
    ayahKey = AyahKey(ayahKey),
    label = label,
    note = note,
    tags = tags,
    createdAt = createdAt,
    updatedAt = updatedAt,
    serverId = serverId,
    pendingSync = pendingSync,
    pendingDelete = pendingDelete,
)
